title: Математически магьосници
description: Прототип на образователна настолна игра за 30–45 мин, 1–4 играчи.
url: "https://math-mages.github.io"
baseurl: "/Math-Mages"   

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
permalink: /:title/

defaults:
  - scope: { path: "" }
    values: { layout: app }
  - scope: { path: "_posts" }
    values: { layout: post }
